<?php
require __DIR__ . '/bootstrap.php';
msrwa_test_load( 'admin' );
msrwa_test_as_editor( 7 );
$_GET = array( 'page' => 'msrwa-jobs', 'status' => 'failed', 's' => '<b>tarte</b>', 'paged' => 9999 );
ob_start(); MSRWA_Admin::jobs(); $html = ob_get_clean();
msrwa_test_contains( $GLOBALS['wpdb']->log(), 'owner_id = 7', 'Editor queries are scoped before reading.' );
msrwa_test_contains( $GLOBALS['wpdb']->log(), "status = 'failed'", 'Status filter reaches the query.' );
msrwa_test_contains( $GLOBALS['wpdb']->log(), 'LIMIT 25 OFFSET 0', 'Page and query size are bounded for empty results.' );
msrwa_test_contains( $html, 'Aucune recette', 'Jobs show a useful empty state.' );
msrwa_test_missing( $html, 'Coût', 'Editorial jobs omit financial information.' );
msrwa_test_missing( $GLOBALS['wpdb']->log(), 'cost_usd', 'Editorial list does not query costs.' );
$GLOBALS['msrwa_test_caps'][] = 'msrwa_view_all';
$GLOBALS['wpdb'] = new MSRWA_Fake_Wpdb();
ob_start(); MSRWA_Admin::jobs(); ob_end_clean();
msrwa_test_contains( $GLOBALS['wpdb']->log(), 'owner_id = 7', 'Legacy view-all does not widen editor scope.' );
msrwa_test_load( 'run', 'batch' );
msrwa_test_assert( ! MSRWA_Run::may_see( array( 'owner_id' => 8 ) ), 'Editor cannot read another owner job.' );
msrwa_test_assert( ! MSRWA_Batch::may_see( array( 'owner_id' => 8 ) ), 'Editor cannot read another owner batch.' );
msrwa_test_missing( $html, 'page=msrwa-settings', 'Editors are not offered administrator settings.' );
msrwa_test_missing( $html, '<b>tarte</b>', 'Search output is sanitized.' );
msrwa_test_as_admin();
$GLOBALS['wpdb'] = new MSRWA_Fake_Wpdb();
$_GET = array( 'page' => 'msrwa-jobs' );
ob_start(); MSRWA_Admin::jobs(); $html = ob_get_clean();
msrwa_test_missing( $GLOBALS['wpdb']->log(), 'owner_id =', 'Administrator can inspect all jobs.' );
foreach ( array( 'Rédaction', 'Jobs', 'Statistiques', 'Planificateur', 'Moteur', 'Réglages' ) as $label ) { msrwa_test_contains( $html, $label, 'Navigation includes ' . $label ); }
msrwa_test_contains( $html, 'aria-current="page"', 'Navigation marks the current page accessibly.' );
ob_start(); MSRWA_Admin::batch_summary( array( array( 'status' => 'running' ), array( 'status' => 'done' ), array( 'status' => 'done' ), array( 'status' => 'failed' ) ) ); $summary = ob_get_clean();
msrwa_test_contains( $summary, 'data-run-count="done">2</strong>', 'Multi-recipe summary counts completed jobs.' );
msrwa_test_contains( $summary, 'data-run-count="running">1</strong>', 'Multi-recipe summary counts active jobs.' );
msrwa_test_contains( $summary, 'data-run-count="queued">0</strong>', 'Empty status is explicitly zero.' );
msrwa_test_assert( 'Échoué' === MSRWA_Admin::run_label( 'failed' ), 'Job labels are readable French.' );
msrwa_test_done( 'admin pages and permissions' );
